name: main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew check

      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          files: ./app/build/reports/kover/reportRelease.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Sign apk
        if: github.event_name == 'push'
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 36.0.0

      - name: Upload release artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: android_release
          path: ${{steps.sign_app.outputs.signedFile}}

  release_apk:
    if: github.event_name == 'push'
    needs: [ test_and_build ]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generate version variables
        run: |
          echo "VERSION_2ND_PLACE=$((GITHUB_RUN_NUMBER/2/10))" >> $GITHUB_ENV
          echo "VERSION_3RD_PLACE=$((GITHUB_RUN_NUMBER/2%10))" >> $GITHUB_ENV

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: android_release

      - name: Rename release file
        run: |
          mv app-release-unsigned-signed.apk remind-me-release-signed.apk

      - name: Create release
        run: |
          gh release create \
          v1.${{ env.VERSION_2ND_PLACE }}.${{ env.VERSION_3RD_PLACE }} \
          $GITHUB_WORKSPACE/*.apk \
          --repo=$GITHUB_REPOSITORY \
          --title=v1.${{ env.VERSION_2ND_PLACE }}.${{ env.VERSION_3RD_PLACE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}